---
title: "Making Table 3"
output: pdf_document
---

```{r}
library(tidyverse)
table_final_test$day_counter_5 <- as.integer(table_final_test$day_counter_5)

#POSITIVE VALUES
next_day5 <- table_final_test %>%
 filter(day_counter_5==2|day_counter_6==2|day_counter_7==2|day_counter_8==2|day_counter_9==2|day_counter_10==2)
prop5pos <- sum(next_day5$ai_retx > 0)/nrow(next_day5)

next_day6 <- table_final_test %>%
 filter(day_counter_6==2|day_counter_7==2|day_counter_8==2|day_counter_9==2|day_counter_10==2)
prop6pos <- sum(next_day6$ai_retx > 0)/nrow(next_day6)

next_day7 <- table_final_test %>%
 filter(day_counter_7==2|day_counter_8==2|day_counter_9==2|day_counter_10==2)
prop7pos <- sum(next_day7$ai_retx > 0)/nrow(next_day7)

next_day8 <- table_final_test %>%
 filter(day_counter_8==2|day_counter_9==2|day_counter_10==2)
prop8pos <- sum(next_day8$ai_retx > 0)/nrow(next_day8)

next_day9 <- table_final_test %>%
 filter(day_counter_9==2|day_counter_10==2)
prop9pos <- sum(next_day9$ai_retx > 0)/nrow(next_day9)

next_day10 <- table_final_test %>%
  filter(day_counter_10 == 2)
prop10pos <- sum(next_day10$ai_retx > 0)/nrow(next_day10)

#NEGATIVE VALUES
next_day5neg <- table_final_test %>%
 filter(day_counter_neg5==2|day_counter_neg6==2|day_counter_neg7==2|day_counter_neg8==2|day_counter_neg9==2|day_counter_neg10==2)
prop5neg <- sum(next_day5neg$ai_retx > 0)/nrow(next_day5neg)

next_day6neg <- table_final_test %>%
 filter(day_counter_neg6==2|day_counter_neg7==2|day_counter_neg8==2|day_counter_neg9==2|day_counter_neg10==2)
prop6neg <- sum(next_day6neg$ai_retx > 0)/nrow(next_day6neg)

next_day7neg <- table_final_test %>%
 filter(day_counter_neg7==2|day_counter_neg8==2|day_counter_neg9==2|day_counter_neg10==2)
prop7neg <- sum(next_day7neg$ai_retx > 0)/nrow(next_day7neg)

next_day8neg <- table_final_test %>%
 filter(day_counter_neg8==2|day_counter_neg9==2|day_counter_neg10==2)
prop8neg <- sum(next_day8neg$ai_retx > 0)/nrow(next_day8neg)

next_day9neg <- table_final_test %>%
 filter(day_counter_neg9==2|day_counter_neg10==2)
prop9neg <- sum(next_day9neg$ai_retx > 0)/nrow(next_day9neg)

next_day10neg <- table_final_test %>%
  filter(day_counter_neg10 == 2)
prop10neg <- sum(next_day10neg$ai_retx > 0)/nrow(next_day10neg)

```


Hard Coding
```{r}
library(tables)
options(kableExtra.latex.load_packages = FALSE)
library(kableExtra)
table3 <- matrix(c(5,prop5pos, prop5neg, "pvalue5", 6, prop6pos,prop6neg,"pvalue6",7,prop7pos,prop7neg,"pvalue7",8,prop8pos,prop8neg,"pvalue8",9,prop9pos,prop9neg,"pvalue9",10,prop10pos,prop10neg,"pvalue10"), ncol = 4, byrow = TRUE)
colnames(table3) <- c("Cutoff (%)", "After + Big Day", "After - Big Day", "p-value")
table3 <- as.table(table3, digits = 2, latex = TRUE)
table3

table4 <- kable(table3, format = "latex", booktabs = TRUE)
table4

table3 %>%
  knitr::kable(caption = "Table 3: Percentage of Stocks with Positive Returns after a Big Day", "latex", digits = 2) %>%
  kableExtra::kable_styling(bootstrap_options = "striped", full_width = FALSE)
table3
#as.data.frame(table3)
#formattable(table3)
#formattable(table3, align = c("l", rep("r", NCOL(table3) - 1)))
```


Making Table 4
```{r}
library(tidyverse)
table_final_test$day_counter_5 <- as.integer(table_final_test$day_counter_5)

#POSITIVE VALUES
next_day5 <- table_final_test %>%
 filter(day_counter_5==2|day_counter_6==2|day_counter_7==2|day_counter_8==2|day_counter_9==2|day_counter_10==2)
mean5pos <- mean(next_day5$ai_retx)

next_day6 <- table_final_test %>%
 filter(day_counter_6==2|day_counter_7==2|day_counter_8==2|day_counter_9==2|day_counter_10==2)
mean6pos <- mean(next_day6$ai_retx)

next_day7 <- table_final_test %>%
 filter(day_counter_7==2|day_counter_8==2|day_counter_9==2|day_counter_10==2)
mean7pos <- mean(next_day7$ai_retx)

next_day8 <- table_final_test %>%
 filter(day_counter_8==2|day_counter_9==2|day_counter_10==2)
mean8pos <- mean(next_day8$ai_retx)

next_day9 <- table_final_test %>%
 filter(day_counter_9==2|day_counter_10==2)
mean9pos <- mean(next_day9$ai_retx)

next_day10 <- table_final_test %>%
  filter(day_counter_10 == 2)
mean10pos <- mean(next_day10$ai_retx)

#NEGATIVE VALUES
next_day5neg <- table_final_test %>%
 filter(day_counter_neg5==2|day_counter_neg6==2|day_counter_neg7==2|day_counter_neg8==2|day_counter_neg9==2|day_counter_neg10==2)
mean5neg <- mean(next_day5neg$ai_retx)

next_day6neg <- table_final_test %>%
 filter(day_counter_neg6==2|day_counter_neg7==2|day_counter_neg8==2|day_counter_neg9==2|day_counter_neg10==2)
mean6neg <- mean(next_day6neg$ai_retx)

next_day7neg <- table_final_test %>%
 filter(day_counter_neg7==2|day_counter_neg8==2|day_counter_neg9==2|day_counter_neg10==2)
mean7neg <- mean(next_day7neg$ai_retx)

next_day8neg <- table_final_test %>%
 filter(day_counter_neg8==2|day_counter_neg9==2|day_counter_neg10==2)
mean8neg <- mean(next_day8neg$ai_retx)

next_day9neg <- table_final_test %>%
 filter(day_counter_neg9==2|day_counter_neg10==2)
mean9neg <- mean(next_day9neg$ai_retx)

next_day10neg <- table_final_test %>%
  filter(day_counter_neg10 == 2)
mean10neg <- mean(next_day10neg$ai_retx)

table4 <- matrix(c(5,mean5pos, mean5neg, "pvalue5", 6, mean6pos,mean6neg,"pvalue6",7,mean7pos,mean7neg,"pvalue7",8,mean8pos,mean8neg,"pvalue8",9,mean9pos,mean9neg,"pvalue9",10,mean10pos,mean10neg,"pvalue10"), ncol = 4, byrow = TRUE)
colnames(table4) <- c("Cutoff (%)", "After + Big Day", "After - Big Day", "p-value")
table4 <- as.table(table4, digits = 2, latex = TRUE)
table4
```

Making Table 5
```{r}
next_day5 <- table_final_test %>%
 filter(day_counter_5==2|day_counter_6==2|day_counter_7==2|day_counter_8==2|day_counter_9==2|day_counter_10==2)
mean_day_1 <- mean(next_day5$ai_retx)

third_day5 <- table_final_test %>%
 filter(day_counter_5==3|day_counter_6==3|day_counter_7==3|day_counter_8==3|day_counter_9==3|day_counter_10==3)
mean_day_2 <- mean(third_day5$ai_retx)

fourth_day5 <- table_final_test %>% 
  filter(day_counter_5==4|day_counter_6==4|day_counter_7==4|day_counter_8==4|day_counter_9==4|day_counter_10==4)
mean_day_3 <- mean(fourth_day5$ai_retx)

fifth_day5 <- table_final_test %>% 
  filter(day_counter_5==5|day_counter_6==5|day_counter_7==5|day_counter_8==5|day_counter_9==5|day_counter_10==5)
mean_day_4 <- mean(fifth_day5$ai_retx)

sixth_day5 <- table_final_test %>% 
  filter(day_counter_5==6|day_counter_6==6|day_counter_7==6|day_counter_8==6|day_counter_9==6|day_counter_10==6)
mean_day_5 <- mean(sixth_day5$ai_retx)

seventh_day5 <- table_final_test %>% 
  filter(day_counter_5==7|day_counter_6==7|day_counter_7==7|day_counter_8==7|day_counter_9==7|day_counter_10==7)
mean_day_6 <- mean(seventh_day5$ai_retx)

eigth_day5 <- table_final_test %>% 
  filter(day_counter_5==8|day_counter_6==8|day_counter_7==8|day_counter_8==8|day_counter_9==8|day_counter_10==8)
mean_day_7 <- mean(eigth_day5$ai_retx)

ninth_day5 <- table_final_test %>% 
  filter(day_counter_5==9|day_counter_6==9|day_counter_7==9|day_counter_8==9|day_counter_9==9|day_counter_10==9)
mean_day_8 <- mean(ninth_day5$ai_retx)

tenth_day5 <- table_final_test %>% 
  filter(day_counter_5==10|day_counter_6==10|day_counter_7==10|day_counter_8==10|day_counter_9==10|day_counter_10==10)
mean_day_9 <- mean(tenth_day5$ai_retx)

eleventh_day5 <- table_final_test %>% 
  filter(day_counter_5==11|day_counter_6==11|day_counter_7==11|day_counter_8==11|day_counter_9==11|day_counter_10==11)
mean_day_10 <- mean(eleventh_day5$ai_retx)

next_day5neg <- table_final_test %>%
 filter(day_counter_neg5==2|day_counter_neg6==2|day_counter_neg7==2|day_counter_neg8==2|day_counter_neg9==2|day_counter_neg10==2)
mean_day_1neg <- mean(next_day5neg$ai_retx)

second_day5neg <- table_final_test %>%
 filter(day_counter_neg5==3|day_counter_neg6==3|day_counter_neg7==3|day_counter_neg8==3|day_counter_neg9==3|day_counter_neg10==3)
mean_day_2neg <- mean(second_day5neg$ai_retx)

third_day5neg <- table_final_test %>%
 filter(day_counter_neg5==4|day_counter_neg6==4|day_counter_neg7==4|day_counter_neg8==4|day_counter_neg9==4|day_counter_neg10==4)
mean_day_3neg <- mean(third_day5neg$ai_retx)

fourth_day5neg <- table_final_test %>%
 filter(day_counter_neg5==5|day_counter_neg6==5|day_counter_neg7==5|day_counter_neg8==5|day_counter_neg9==5|day_counter_neg10==5)
mean_day_4neg <- mean(fourth_day5neg$ai_retx)

fifth_day5neg <- table_final_test %>%
 filter(day_counter_neg5==6|day_counter_neg6==6|day_counter_neg7==6|day_counter_neg8==6|day_counter_neg9==6|day_counter_neg10==6)
mean_day_5neg <- mean(fifth_day5neg$ai_retx)

sixth_day5neg <- table_final_test %>%
 filter(day_counter_neg5==7|day_counter_neg6==7|day_counter_neg7==7|day_counter_neg8==7|day_counter_neg9==7|day_counter_neg10==7)
mean_day_6neg <- mean(sixth_day5neg$ai_retx)

seventh_day5neg <- table_final_test %>%
 filter(day_counter_neg5==8|day_counter_neg6==8|day_counter_neg7==8|day_counter_neg8==8|day_counter_neg9==8|day_counter_neg10==8)
mean_day_7neg <- mean(seventh_day5neg$ai_retx)

eigth_day5neg <- table_final_test %>%
 filter(day_counter_neg5==9|day_counter_neg6==9|day_counter_neg7==9|day_counter_neg8==9|day_counter_neg9==9|day_counter_neg10==9)
mean_day_8neg <- mean(eigth_day5neg$ai_retx)

ninth_day5neg <- table_final_test %>%
 filter(day_counter_neg5==10|day_counter_neg6==10|day_counter_neg7==10|day_counter_neg8==10|day_counter_neg9==10|day_counter_neg10==10)
mean_day_9neg <- mean(ninth_day5neg$ai_retx)

tenth_day5neg <- table_final_test %>%
 filter(day_counter_neg5==11|day_counter_neg6==11|day_counter_neg7==11|day_counter_neg8==11|day_counter_neg9==11|day_counter_neg10==11)
mean_day_10neg <- mean(tenth_day5neg$ai_retx)

table5 <- matrix(c("1",100*(mean_day_1), 100*(mean_day_1neg), 2, 100*(mean_day_2),100*(mean_day_2neg),3,100*(mean_day_3),100*(mean_day_3neg),4,100*(mean_day_4),100*(mean_day_4neg),5,100*(mean_day_5),100*(mean_day_5neg),6,100*(mean_day_6),100*(mean_day_6neg),7,100*(mean_day_7),100*(mean_day_7neg),8,100*(mean_day_8),100*(mean_day_8neg),9,100*(mean_day_9),100*(mean_day_9neg),10,100*(mean_day_10),100*(mean_day_10neg)), ncol = 3, byrow = TRUE)
colnames(table5) <- c("Day", "+ Big Day", "- Big Day")
table5 <- as.table(table5)
table5



```